schema:
  - https://cms.cesarbenavides.com/index.php?graphql:
      headers:
          origin: https://localhost:3000
generates:
  ./types/wp.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - 'typescript-nhost'
    config:
      withRefetchFn: true
preview_file_uploads:
  enabled: true
  protocols:
    multipart:
      enabled: true
      mode: stream
      limits:
        max_file_size: 1mb
        max_files: 10